import pandas as pd
import os

data = [
    # AI (30)
    ("OpenAI announces GPT-5 release date and features", "AI"),
    ("Google DeepMind solves complex protein folding", "AI"),
    ("Anthropic's Claude 3 outperforms rivals in reasoning", "AI"),
    ("Meta open-sources new Llama 3 weights", "AI"),
    ("Midjourney V6 generates photorealistic images", "AI"),
    ("AI tool helps doctors diagnose cancer earlier", "AI"),
    ("Nvidia's new AI chip is 30x faster", "AI"),
    ("Will AI replace software engineers? A new study says no", "AI"),
    ("How ChatGPT is changing the education landscape", "AI"),
    ("Machine learning algorithm predicts weather with 99% accuracy", "AI"),
    ("Microsoft integrates Copilot into all Office apps", "AI"),
    ("Apple researcher publishes paper on on-device LLMs", "AI"),
    ("AI startup raises $100M for autonomous coding agents", "AI"),
    ("The ethics of AI: bias in facial recognition", "AI"),
    ("Robotics company uses AI to teach robots how to walk", "AI"),
    ("AI-generated music wins major industry award", "AI"),
    ("Hugging Face hits 1 million models hosted", "AI"),
    ("Sam Altman talks about the future of AGI", "AI"),
    ("New neural network architecture reduces hallucination", "AI"),
    ("AI video generator Sora takes the internet by storm", "AI"),
    ("Can AI solve climate change? Researchers say yes", "AI"),
    ("The history of natural language processing", "AI"),
    ("Top 5 prompt engineering tips for developers", "AI"),
    ("AI agent beats world champion at complex strategy game", "AI"),
    ("Startups pivot to generative AI to secure funding", "AI"),
    ("Government introduces new AI safety regulations", "AI"),
    ("How reinforcement learning works under the hood", "AI"),
    ("AI data centers are consuming massive amounts of power", "AI"),
    ("Open-source AI community rallies against closed models", "AI"),
    ("Using computer vision to track endangered species", "AI"),

    # Cybersecurity (30)
    ("Massive data breach exposes 50 million user passwords", "Cybersecurity"),
    ("New ransomware gang targets hospitals in the US", "Cybersecurity"),
    ("Zero-day vulnerability discovered in popular web browser", "Cybersecurity"),
    ("Hackers steal $50M in crypto exchange exploit", "Cybersecurity"),
    ("How to protect your company against phishing attacks", "Cybersecurity"),
    ("VPN provider logs user data despite zero-log policy", "Cybersecurity"),
    ("FBI takes down major dark web marketplace", "Cybersecurity"),
    ("Security researchers find flaw in smart home locks", "Cybersecurity"),
    ("Why multi-factor authentication is no longer enough", "Cybersecurity"),
    ("State-sponsored hackers infiltrate government grid", "Cybersecurity"),
    ("The rise of AI-powered cyber attacks", "Cybersecurity"),
    ("Update your iPhone now to patch critical security flaw", "Cybersecurity"),
    ("Malware hidden in popular npm package downloaded millions of times", "Cybersecurity"),
    ("Cybersecurity startup raises Series A to fight deepfakes", "Cybersecurity"),
    ("How end-to-end encryption works in messaging apps", "Cybersecurity"),
    ("DDoS attack takes down major gaming servers", "Cybersecurity"),
    ("Password manager hacked, source code stolen", "Cybersecurity"),
    ("The biggest cybersecurity threats for 2026", "Cybersecurity"),
    ("How to conduct a security audit for your web app", "Cybersecurity"),
    ("Supply chain attack affects thousands of businesses", "Cybersecurity"),
    ("Cybersecurity experts warn against using public Wi-Fi", "Cybersecurity"),
    ("New legislation requires companies to report breaches within 24 hours", "Cybersecurity"),
    ("White-hat hacker rewarded $1M bug bounty", "Cybersecurity"),
    ("The role of a Chief Information Security Officer today", "Cybersecurity"),
    ("Ransomware demands hit record high in Q3", "Cybersecurity"),
    ("Social engineering tactics are getting more sophisticated", "Cybersecurity"),
    ("Is biometric security actually safe?", "Cybersecurity"),
    ("Cloud security misconfiguration leads to massive data leak", "Cybersecurity"),
    ("IoT devices are the weak link in home networks", "Cybersecurity"),
    ("Cyber warfare: The invisible battleground", "Cybersecurity"),

    # Startups (30)
    ("Fintech startup Stripe valuation hits $65 billion", "Startups"),
    ("Y Combinator announces new batch of winter startups", "Startups"),
    ("Founders share the secret to finding product-market fit", "Startups"),
    ("Venture capital funding drops 20% in Q1", "Startups"),
    ("How to write a pitch deck that gets funded", "Startups"),
    ("SaaS startup hits $10M ARR in just two years", "Startups"),
    ("Why 90% of startups fail and how to avoid it", "Startups"),
    ("Bootstrapped founder sells company for $50M", "Startups"),
    ("Sequoia Capital launches new seed stage fund", "Startups"),
    ("The rise of solopreneurship in the tech industry", "Startups"),
    ("Startup founder steps down amid board dispute", "Startups"),
    ("Healthtech startup revolutionizes remote patient monitoring", "Startups"),
    ("Cleantech startups see massive surge in investment", "Startups"),
    ("How to hire your first 5 employees as a founder", "Startups"),
    ("Startup accelerator Techstars opens applications", "Startups"),
    ("Space startup successfully launches micro-satellite", "Startups"),
    ("Edtech company pivots strategy after market shifts", "Startups"),
    ("The pros and cons of taking venture capital", "Startups"),
    ("Proptech startup aims to disrupt real estate market", "Startups"),
    ("Startup hub moves from Silicon Valley to Miami", "Startups"),
    ("How to value your early-stage startup", "Startups"),
    ("Female founders receive record high percentage of VC funding", "Startups"),
    ("Startup culture: Free snacks vs real benefits", "Startups"),
    ("Agtech startup uses drones to monitor crop health", "Startups"),
    ("Logistics startup solves last-mile delivery challenge", "Startups"),
    ("The impact of interest rates on startup valuations", "Startups"),
    ("How to acquire your first 1000 users", "Startups"),
    ("Startup exit: IPO vs Acquisition", "Startups"),
    ("Web3 startup returns funds to investors", "Startups"),
    ("Foodtech startup creates convincing plant-based steak", "Startups"),

    # Gadgets (30)
    ("Apple unveils the new iPhone 17 with holographic display", "Gadgets"),
    ("Samsung's new foldable phone is thinner than ever", "Gadgets"),
    ("Sony releases highly anticipated PlayStation 6 Pro", "Gadgets"),
    ("Review: The best noise-canceling headphones of the year", "Gadgets"),
    ("Smartwatch tracks blood sugar without needles", "Gadgets"),
    ("DJI announces new drone with 8K camera", "Gadgets"),
    ("Are VR headsets finally ready for mainstream consumers?", "Gadgets"),
    ("Google Pixel 10 focuses entirely on computational photography", "Gadgets"),
    ("New mechanical keyboard features customizable OLED keys", "Gadgets"),
    ("Smart ring tracks sleep better than a smartwatch", "Gadgets"),
    ("Laptop battery life hits 30 hours with new ARM chip", "Gadgets"),
    ("E-ink tablet mimics the feel of real paper perfectly", "Gadgets"),
    ("Nintendo Switch 2 specs leaked online", "Gadgets"),
    ("Portable projector turns any wall into a 100-inch screen", "Gadgets"),
    ("Smart glasses finally look like regular glasses", "Gadgets"),
    ("Review: Is the new iPad Pro a laptop replacement?", "Gadgets"),
    ("Action camera shoots 360-degree video in low light", "Gadgets"),
    ("Wireless earbuds now feature real-time translation", "Gadgets"),
    ("Retro gaming handheld plays all classic cartridges", "Gadgets"),
    ("Smart home hub combines matter and thread support", "Gadgets"),
    ("High-end espresso machine uses pressure profiling", "Gadgets"),
    ("Ultrawide monitor curve reduces eye strain", "Gadgets"),
    ("The evolution of the computer mouse", "Gadgets"),
    ("Foldable laptops are cool, but are they practical?", "Gadgets"),
    ("New dashcam records in 4K with cloud backup", "Gadgets"),
    ("Smart scale measures body composition accurately", "Gadgets"),
    ("Graphics card prices finally return to MSRP", "Gadgets"),
    ("Electric scooter features regenerative braking", "Gadgets"),
    ("Robotic vacuum now mops and empties its own water", "Gadgets"),
    ("The best portable power banks for travel", "Gadgets"),

    # Software (30)
    ("Python 3.14 released with massive speed improvements", "Software"),
    ("Microsoft Windows 12 focuses on cloud integration", "Software"),
    ("Ubuntu 26.04 LTS brings new desktop environment", "Software"),
    ("React 19 introduces new state management hooks", "Software"),
    ("Docker announces new pricing model for enterprises", "Software"),
    ("PostgreSQL 17 adds advanced JSON querying features", "Software"),
    ("The debate between monolithic and microservices architecture", "Software"),
    ("VS Code update adds built-in database explorer", "Software"),
    ("Git 3.0 rewrites the history tree structure", "Software"),
    ("How Rust is slowly replacing C++ in critical systems", "Software"),
    ("Vite becomes the most popular frontend build tool", "Software"),
    ("Kubernetes simplifies cluster management in new release", "Software"),
    ("Figma acquires prominent design software competitor", "Software"),
    ("Notion adds offline mode after years of user requests", "Software"),
    ("Tailwind CSS version 4 removes the need for configuration", "Software"),
    ("The best open-source alternatives to Adobe Creative Cloud", "Software"),
    ("How to optimize your SQL queries for better performance", "Software"),
    ("Linux kernel drops support for legacy hardware", "Software"),
    ("Redis changes license, prompting open-source fork", "Software"),
    ("Top 10 VS Code extensions for productivity", "Software"),
    ("WebAssembly enables desktop-class apps in the browser", "Software"),
    ("Why developers are moving away from SPAs to server-side rendering", "Software"),
    ("Android 16 developer preview reveals privacy changes", "Software"),
    ("Slack completely redesigns its user interface", "Software"),
    ("How to implement CI/CD for your side project", "Software"),
    ("The rise of local-first software development", "Software"),
    ("Next.js update improves static site generation speed", "Software"),
    ("Jira alternatives for agile project management", "Software"),
    ("How garbage collection works in Java", "Software"),
    ("An introduction to functional programming concepts", "Software")
]

os.makedirs('data', exist_ok=True)
df = pd.DataFrame(data, columns=['headline', 'category'])
df.to_csv('data/headlines.csv', index=False)
print("✅ Successfully generated data/headlines.csv with 150 rows!")